#!/usr/bin/env python3
"""Generate first-class clean-route pages for Sports Passport.

The legacy root HTML files remain the editable page templates. This generator creates
real GitHub Pages files for the public clean URLs so normal navigation no longer
needs the 404/fetch/document.write bootstrap. The bootstrap remains as a compatibility
fallback for stale or unknown deep URLs.
"""
from __future__ import annotations

from pathlib import Path
from urllib.parse import parse_qs, urlsplit
import html as html_lib
import json
import re
import shutil
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
PUBLIC_ORIGIN = "https://sports.alexlford.com"
MARKER = "<!-- GENERATED BY tools/generate_routes.py; DO NOT EDIT -->"

STATIC_ROUTES = {
    "/about/": "about.html",
    "/years/": "annuals.html",
    "/teams/": "teams.html",
    "/venues/": "venues.html",
    "/geography/": "geography.html",
    "/geography/map/": "venue-map.html",
    "/journeys/": "journeys.html",
    "/favorites/": "favorites.html",
    "/analytics/": "lifetime-analytics.html",
    "/hall-of-fame/": "hall-of-fame.html",
    "/search/": "search.html",
}

DYNAMIC_ROUTE_INFO = {
    "years": {"source": "year.html", "param": "y", "public_param": "year"},
    "events": {"source": "event.html", "param": "id", "public_param": "event"},
    "teams": {"source": "team-profile.html", "param": "t", "public_param": "team"},
    "venues": {"source": "venue-profile.html", "param": "v", "public_param": "venue"},
    "journeys": {"source": "journey-profile.html", "param": "j", "public_param": "journey"},
    "chapters": {"source": "phase.html", "param": "p", "public_param": "chapter"},
}

LEGACY_QUERY_ALIASES = {
    "years": ("year", "y"),
    "events": ("event", "id"),
    "teams": ("team", "t"),
    "venues": ("venue", "v"),
    "journeys": ("journey", "j"),
    "chapters": ("chapter", "p"),
}


def load_json(name: str):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def slug(value: str) -> str:
    value = str(value).lower().replace("&", "and")
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")


def load_events() -> list[dict]:
    manifest = load_json("events.json")
    events: list[dict] = []
    for chunk in manifest.get("chunks", []):
        events.extend(load_json(chunk))
    return events


def load_venues() -> list[dict]:
    venues = load_json("venues.json")
    by_key = {v["key"]: v for v in venues}
    additions_path = DATA / "venue-additions.json"
    if additions_path.is_file():
        for venue in json.loads(additions_path.read_text(encoding="utf-8")):
            by_key[venue["key"]] = {**by_key.get(venue["key"], {}), **venue}
    return list(by_key.values())


def ensure_html_lang(source: str) -> str:
    return re.sub(r"<html(?![^>]*\blang\s*=)", '<html lang="en"', source, count=1, flags=re.I)


def replace_or_insert_title(source: str, title: str | None) -> str:
    if not title:
        return source
    safe = html_lib.escape(title, quote=False)
    if re.search(r"<title>.*?</title>", source, flags=re.I | re.S):
        return re.sub(r"<title>.*?</title>", f"<title>{safe}</title>", source, count=1, flags=re.I | re.S)
    return re.sub(r"<head([^>]*)>", rf"<head\1><title>{safe}</title>", source, count=1, flags=re.I)


def strip_generated_head_bits(source: str) -> str:
    source = re.sub(r"<base\s+href=[\"']/[\"']\s*/?>", "", source, flags=re.I)
    source = re.sub(r"<link[^>]+href=[\"']/assets/accessibility\.css[\"'][^>]*>", "", source, flags=re.I)
    source = re.sub(r"<link[^>]+rel=[\"']canonical[\"'][^>]*>", "", source, flags=re.I)
    source = re.sub(r"<script[^>]+src=[\"']/assets/clean-urls\.js[\"'][^>]*>\s*</script>", "", source, flags=re.I)
    source = re.sub(r"<script[^>]+src=[\"']assets/clean-urls\.js[\"'][^>]*>\s*</script>", "", source, flags=re.I)
    return source


def inject_description(source: str, description: str | None) -> str:
    if not description:
        return source
    safe = html_lib.escape(description, quote=True)
    pattern = r"<meta\s+name=[\"']description[\"'][^>]*>"
    replacement = f'<meta name="description" content="{safe}">'
    if re.search(pattern, source, flags=re.I):
        return re.sub(pattern, replacement, source, count=1, flags=re.I)
    return re.sub(r"<head([^>]*)>", rf"<head\1>{replacement}", source, count=1, flags=re.I)


def legacy_query_redirect(section: str) -> str:
    aliases = LEGACY_QUERY_ALIASES.get(section)
    if not aliases:
        return ""
    keys = json.dumps(list(aliases))
    return f"""<script>(function(){{
const p=new URLSearchParams(location.search),keys={keys};
for(const key of keys){{const value=p.get(key);if(value){{location.replace('/{section}/'+encodeURIComponent(value)+'/'+(location.hash||''));return;}}}}
}})();</script>"""


def route_prelude(public_path: str, source_file: str, params: dict[str, str]) -> str:
    params_json = json.dumps(params, separators=(",", ":"))
    temp = public_path
    if params:
        query = "&".join(f"{k}={html_lib.escape(str(v), quote=True)}" for k, v in params.items())
        temp = f"{public_path}?{query}"
    public_json = json.dumps(public_path)
    source_json = json.dumps(source_file)
    temp_json = json.dumps(temp)
    return f"""<script>
window.SPORTS_CLEAN_ROUTE=true;
window.SPORTS_ROUTE_PUBLIC_URL={public_json};
window.SPORTS_ROUTE_SOURCE={source_json};
window.SPORTS_ROUTE_PARAMS={params_json};
window.SPORTS_ROUTE_HASH=location.hash||'';
{f'history.replaceState(null,\"\",{temp_json}+window.SPORTS_ROUTE_HASH);' if params else ''}
</script>"""


def route_restore(dynamic: bool) -> str:
    if not dynamic:
        return ""
    return """<script>(function(){
const clean=window.SPORTS_ROUTE_PUBLIC_URL||location.pathname,hash=window.SPORTS_ROUTE_HASH||'';
let tries=0;
function ready(){const app=document.querySelector('#app');return (app&&app.children.length>0)||document.querySelector('.event-hero,.hero');}
function finish(){if(ready()||tries++>200){history.replaceState(null,'',clean+hash);return;}setTimeout(finish,25);}
finish();
})();</script>"""


def render_from_template(
    source_file: str,
    public_path: str,
    params: dict[str, str] | None = None,
    *,
    title: str | None = None,
    description: str | None = None,
    query_redirect_section: str | None = None,
) -> str:
    params = params or {}
    source = (ROOT / source_file).read_text(encoding="utf-8")
    source = strip_generated_head_bits(ensure_html_lang(source))
    source = replace_or_insert_title(source, title)
    source = inject_description(source, description)
    canonical = f'{PUBLIC_ORIGIN}{public_path}'
    head_bits = (
        f"\n{MARKER}\n"
        '<base href="/">\n'
        '<link rel="stylesheet" href="/assets/accessibility.css">\n'
        f'<link rel="canonical" href="{html_lib.escape(canonical, quote=True)}">\n'
        + (legacy_query_redirect(query_redirect_section) if query_redirect_section else "")
        + "\n"
        + route_prelude(public_path, source_file, params)
        + "\n"
    )
    source = re.sub(r"<head([^>]*)>", rf"<head\1>{head_bits}", source, count=1, flags=re.I)
    tail = '\n<script src="/assets/clean-urls.js"></script>\n' + route_restore(bool(params)) + "\n"
    source = re.sub(r"</body>", tail + "</body>", source, count=1, flags=re.I)
    return source


def redirect_page(public_path: str, destination: str, section: str | None = None) -> str:
    query_redirect = legacy_query_redirect(section) if section else ""
    canonical = f"{PUBLIC_ORIGIN}{destination}"
    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
{MARKER}
<link rel="canonical" href="{canonical}">
<meta name="robots" content="noindex,follow">
<title>Sports Passport</title>
{query_redirect}
<script>location.replace({json.dumps(destination)}+(location.hash||''));</script>
</head><body><p><a href="{destination}">Continue to Sports Passport</a></p></body></html>
"""


def write_route(public_path: str, content: str) -> None:
    rel = public_path.strip("/")
    target_dir = ROOT if not rel else ROOT / rel
    target_dir.mkdir(parents=True, exist_ok=True)
    (target_dir / "index.html").write_text(content, encoding="utf-8")


def reset_owned_routes() -> None:
    for name in ("about", "years", "events", "teams", "venues", "geography", "journeys", "chapters", "favorites", "analytics", "hall-of-fame", "search"):
        path = ROOT / name
        if path.exists():
            shutil.rmtree(path)


def build_dynamic_records():
    events = load_events()
    aliases = load_json("team-aliases.json")
    venues = load_venues()
    journeys = load_json("journeys.json")
    phases = load_json("phases.json")
    config = load_json("config.json")

    canonical_teams = sorted({aliases.get(team, team) for event in events for team in event.get("teams", [])})
    years = list(range(int(config["archive_start_year"]), int(config["current_year"]) + 1))

    return {
        "years": [(str(year), {"y": str(year)}, f"{year} Annual Edition | Sports Passport", f"Alex Ford’s {year} Sports Passport annual edition, with documented live games, venues, teams, and year-specific analytics.") for year in years],
        "events": [(str(event["id"]), {"id": str(event["id"])}, f"{' vs '.join(event.get('teams', [])) or 'Event'} | Sports Passport", f"{event.get('date', '')} · {event.get('venue_recorded', 'Venue not recorded')} · {event.get('city', '')}".strip(" ·")) for event in events if event.get("id")],
        "teams": [(slug(team), {"t": slug(team)}, f"{team} | Sports Passport", f"{team} appearances, venues, annual records, and signature moments in Alex Ford’s Sports Passport archive.") for team in canonical_teams],
        "venues": [(str(venue["slug"]), {"v": str(venue["slug"])}, f"{venue.get('display_name', venue['slug'])} | Sports Passport", f"{venue.get('display_name', venue['slug'])} in {venue.get('city', '')}: visits, teams, signature moments, and archive history from Alex Ford’s Sports Passport." ) for venue in venues if venue.get("slug")],
        "journeys": [(str(j["key"]), {"j": str(j["key"])}, f"{j.get('title', j['key'])} | Sports Passport", j.get("description") or "A recurring thread in Alex Ford’s Sports Passport archive.") for j in journeys if j.get("key")],
        "chapters": [(str(p["key"]), {"p": str(p["key"])}, f"{p.get('title', p['key'])} | Sports Passport Life Chapters", p.get("deck") or "A life chapter in Alex Ford’s Sports Passport archive.") for p in phases if p.get("key")],
    }


def rewrite_sitemap_to_deep_routes() -> None:
    path = ROOT / "sitemap.xml"
    if not path.is_file():
        return
    ns = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    ET.register_namespace("", ns["sm"])
    tree = ET.parse(path)
    root = tree.getroot()
    param_to_section = {info["public_param"]: section for section, info in DYNAMIC_ROUTE_INFO.items()}
    for loc in root.findall("sm:url/sm:loc", ns):
        if not loc.text:
            continue
        parsed = urlsplit(loc.text.strip())
        if f"{parsed.scheme}://{parsed.netloc}" != PUBLIC_ORIGIN or not parsed.query:
            continue
        params = parse_qs(parsed.query)
        if len(params) != 1:
            continue
        key, values = next(iter(params.items()))
        section = param_to_section.get(key)
        if not section or len(values) != 1:
            continue
        loc.text = f"{PUBLIC_ORIGIN}/{section}/{values[0]}/"
    ET.indent(tree, space="  ")
    xml = ET.tostring(root, encoding="unicode")
    path.write_text('<?xml version="1.0" encoding="UTF-8"?>\n' + xml + '\n', encoding="utf-8")


def main() -> None:
    reset_owned_routes()

    for public_path, source_file in STATIC_ROUTES.items():
        section = public_path.strip("/").split("/")[0]
        content = render_from_template(
            source_file,
            public_path,
            query_redirect_section=section if section in LEGACY_QUERY_ALIASES else None,
        )
        write_route(public_path, content)

    write_route("/events/", redirect_page("/events/", "/years/", "events"))
    write_route("/chapters/", redirect_page("/chapters/", "/journeys/", "chapters"))

    dynamic = build_dynamic_records()
    for section, records in dynamic.items():
        info = DYNAMIC_ROUTE_INFO[section]
        for identity, params, title, description in records:
            public_path = f"/{section}/{identity}/"
            content = render_from_template(
                info["source"],
                public_path,
                params,
                title=title,
                description=description,
            )
            write_route(public_path, content)

    rewrite_sitemap_to_deep_routes()
    total = sum(len(records) for records in dynamic.values()) + len(STATIC_ROUTES) + 2
    print(f"Generated {total} first-class clean route pages.")


if __name__ == "__main__":
    main()
