#!/usr/bin/env python3
from collections import defaultdict
from pathlib import Path
from urllib.parse import urlsplit
import json
import re
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'data'
PUBLIC_ORIGIN = 'https://sports.alexlford.com'
MARKER = '<!-- GENERATED BY tools/generate_routes.py; DO NOT EDIT -->'
errors = []


def load_json(name):
    return json.loads((DATA / name).read_text(encoding='utf-8'))


def slug(value):
    value = str(value).lower().replace('&', 'and')
    value = re.sub(r'[^a-z0-9]+', '-', value)
    return value.strip('-')


def check_unique(label, pairs):
    seen = defaultdict(list)
    for identity, source in pairs:
        seen[str(identity)].append(str(source))
    for identity, sources in sorted(seen.items()):
        if not identity:
            errors.append(f'{label}: blank route identity from {sources}')
        elif len(sources) > 1:
            errors.append(f'{label}: duplicate route identity {identity!r}: ' + ' | '.join(sources))
        if '/' in identity or '?' in identity or '#' in identity:
            errors.append(f'{label}: unsafe route identity {identity!r}')


def generated_path(section, identity=None):
    path = ROOT / section
    if identity is not None:
        path = path / str(identity)
    return path / 'index.html'


def check_generated(section, identity, source_file, param, public_path):
    path = generated_path(section, identity)
    if not path.is_file():
        errors.append(f'generated route missing: {public_path}')
        return
    text = path.read_text(encoding='utf-8')
    for token in (
        MARKER,
        f'window.SPORTS_ROUTE_PUBLIC_URL="{public_path}"',
        f'window.SPORTS_ROUTE_SOURCE="{source_file}"',
        f'"{param}":"{identity}"',
        f'<link rel="canonical" href="{PUBLIC_ORIGIN}{public_path}">',
    ):
        if token not in text:
            errors.append(f'generated route {public_path} missing token: {token}')
    if 'route-bootstrap.js' in text:
        errors.append(f'generated route {public_path} must not depend on route-bootstrap.js')


manifest = load_json('events.json')
events = []
for file_name in manifest.get('chunks', []):
    events.extend(load_json(file_name))

aliases = load_json('team-aliases.json')
venues = load_json('venues.json')
try:
    additions = load_json('venue-additions.json')
except FileNotFoundError:
    additions = []
venue_by_key = {v['key']: v for v in venues}
for venue in additions:
    venue_by_key[venue['key']] = {**venue_by_key.get(venue['key'], {}), **venue}
venues = list(venue_by_key.values())
journeys = load_json('journeys.json')
phases = load_json('phases.json')
config = load_json('config.json')

check_unique('event', [(e.get('id'), f"{e.get('date')} {' vs '.join(e.get('teams', []))}") for e in events])
canonical_teams = sorted({aliases.get(team, team) for e in events for team in e.get('teams', [])})
check_unique('team slug', [(slug(team), team) for team in canonical_teams])
check_unique('venue slug', [(v.get('slug'), f"{v.get('key')} / {v.get('display_name')}") for v in venues if v.get('slug') is not None])
check_unique('venue key', [(v.get('key'), v.get('display_name')) for v in venues])
check_unique('journey key', [(j.get('key'), j.get('title')) for j in journeys])
check_unique('chapter key', [(p.get('key'), p.get('title')) for p in phases])

years = sorted({int(e['year']) for e in events if e.get('year') is not None})
start = int(config['archive_start_year'])
current = int(config['current_year'])
for year in years:
    if year < start or year > current:
        errors.append(f'year route: event year {year} is outside configured archive range {start}-{current}')
for year in range(start, current + 1):
    if year not in years:
        errors.append(f'year route: configured public year {year} has no archive events')

valid = {
    'years': {str(year) for year in years},
    'events': {str(e.get('id')) for e in events if e.get('id')},
    'teams': {slug(team) for team in canonical_teams},
    'venues': {str(v.get('slug')) for v in venues if v.get('slug')},
    'journeys': {str(j.get('key')) for j in journeys if j.get('key')},
    'chapters': {str(p.get('key')) for p in phases if p.get('key')},
}
route_meta = {
    'years': ('year.html', 'y'),
    'events': ('event.html', 'id'),
    'teams': ('team-profile.html', 't'),
    'venues': ('venue-profile.html', 'v'),
    'journeys': ('journey-profile.html', 'j'),
    'chapters': ('phase.html', 'p'),
}

for section, identities in valid.items():
    source_file, param = route_meta[section]
    for identity in sorted(identities):
        public_path = f'/{section}/{identity}/'
        check_generated(section, identity, source_file, param, public_path)

for section in ('about','years','events','teams','venues','geography','journeys','chapters','favorites','analytics','hall-of-fame'):
    path = generated_path(section)
    if not path.is_file():
        errors.append(f'section route missing: /{section}/')
    elif MARKER not in path.read_text(encoding='utf-8'):
        errors.append(f'section route is not generator-owned: /{section}/')
if not generated_path('geography/map').is_file():
    errors.append('section route missing: /geography/map/')

sitemap = ROOT / 'sitemap.xml'
if not sitemap.is_file():
    errors.append('sitemap identity audit: missing sitemap.xml')
else:
    try:
        tree = ET.parse(sitemap)
        ns = {'sm': 'http://www.sitemaps.org/schemas/sitemap/0.9'}
        sitemap_urls = [node.text.strip() for node in tree.findall('sm:url/sm:loc', ns) if node.text and node.text.strip()]
        for url in sitemap_urls:
            parsed = urlsplit(url)
            if f'{parsed.scheme}://{parsed.netloc}' != PUBLIC_ORIGIN:
                continue
            if parsed.query:
                errors.append(f'sitemap must use deep static URLs, not query routing: {url}')
                continue
            parts = parsed.path.split('/')
            parts = [part for part in parts if part]
            if len(parts) != 2 or parts[0] not in valid:
                continue
            section, identity = parts
            if identity not in valid[section]:
                errors.append(f'sitemap identity audit: stale {section} identity {identity!r}: {url}')
            if not generated_path(section, identity).is_file():
                errors.append(f'sitemap points to missing generated page: {url}')
    except Exception as exc:
        errors.append(f'sitemap identity audit: could not parse sitemap.xml: {exc}')

route = (ROOT / 'assets' / 'route-bootstrap.js').read_text(encoding='utf-8')
for token in (
    "first === 'years'", "first === 'events'", "first === 'teams'", "first === 'venues'",
    "first === 'journeys'", "first === 'chapters'",
    "template = 'year.html'", "template = 'event.html'", "template = 'team-profile.html'",
    "template = 'venue-profile.html'", "template = 'journey-profile.html'", "template = 'phase.html'",
):
    if token not in route:
        errors.append(f'compatibility bootstrap missing identity mapping: {token}')

if errors:
    print('\n'.join('ERROR: ' + e for e in errors))
    sys.exit(1)

print(
    f'OK: generated first-class routes validated for {len(events)} events, '
    f'{len(canonical_teams)} canonical teams, {len(venues)} venues, '
    f'{len(journeys)} journeys, {len(phases)} chapters, and {len(years)} annual editions.'
)
