#!/usr/bin/env python3
from pathlib import Path
import json
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = "https://sports.alexlford.com"
MARKER = "<!-- GENERATED BY tools/generate_routes.py; DO NOT EDIT -->"
errors = []

def load_json(path):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))

manifest = load_json("data/events.json")
events = []
for chunk in manifest.get("chunks", []):
    events.extend(load_json(f"data/{chunk}"))
by_id = {e.get("id"): e for e in events if e.get("id")}
rankings = load_json("data/curated-rankings.json")
ranked = rankings.get("sports_experiences", [])

page = ROOT / "event.html"
if not page.is_file():
    errors.append("missing event.html exact-record template")
else:
    text = page.read_text(encoding="utf-8")
    if "String(event.source" in text or "source||''" in text:
        errors.append("event.html must not infer evidence class from source-string wording")
    for token, label in (
        ("new URLSearchParams(location.search).get('id')", "event id template handling"),
        ("D.load('events')", "event archive loading"),
        ("D.load('venues')", "venue context loading"),
        ("D.load('curated-rankings')", "Personal Canon context loading"),
        ("event.html?id=", "chronological event-to-event navigation"),
        ("year.html?y=", "annual-edition context link"),
        ("team-profile.html?t=", "team-profile context links"),
        ("venue-profile.html?v=", "venue-profile context links"),
        ('id="share-event"', "Event Passport share action"),
        ('id="copy-event"', "Event Passport copy-link action"),
        ("event.competition_round", "optional competition-round rendering"),
        ("event.site_type", "optional site-type rendering"),
        ("event.personal_note", "optional personal-note rendering"),
        ("Event ID", "stable event identifier rendering"),
        ("D.evidenceLabel(event)", "structured evidence rendering"),
        ("Evidence provenance", "evidence provenance rendering"),
    ):
        if token not in text:
            errors.append(f"event.html missing {label}")

clean_urls = ROOT / "assets" / "clean-urls.js"
if not clean_urls.is_file():
    errors.append("missing clean URL normalizer")
else:
    clean_text = clean_urls.read_text(encoding="utf-8")
    for token in (
        "/events/${encode(p.get('id'))}/",
        "'/events/': ['event','id']",
        "function queryCleanRoute(url)",
    ):
        if token not in clean_text:
            errors.append(f"clean URL normalizer missing exact-event route support: {token}")
    if "/events/?event=" in clean_text:
        errors.append("clean URL normalizer must not emit legacy query-form event URLs")

route_entry = ROOT / "events" / "index.html"
if not route_entry.is_file():
    errors.append("missing /events/ compatibility route entry")
elif MARKER not in route_entry.read_text(encoding="utf-8"):
    errors.append("/events/ compatibility route entry must be generator-owned")

for event_id in sorted(by_id):
    route = ROOT / "events" / event_id / "index.html"
    if not route.is_file():
        errors.append(f"missing first-class Event Passport route: /events/{event_id}/")
        continue
    route_text = route.read_text(encoding="utf-8")
    for token in (
        MARKER,
        f'window.SPORTS_ROUTE_PUBLIC_URL="/events/{event_id}/"',
        'window.SPORTS_ROUTE_SOURCE="event.html"',
        f'"id":"{event_id}"',
        f'<link rel="canonical" href="{ORIGIN}/events/{event_id}/">',
    ):
        if token not in route_text:
            errors.append(f"generated Event Passport /events/{event_id}/ missing token: {token}")
    if "route-bootstrap.js" in route_text:
        errors.append(f"first-class Event Passport /events/{event_id}/ must not load the compatibility bootstrap")

for item in ranked:
    event_id = item.get("event_id")
    if not event_id or event_id not in by_id:
        errors.append(f"ranked experience #{item.get('rank')} does not resolve to an archive event")

linked_pages = [
    "favorites.html",
    "hall-of-fame.html",
    "phase.html",
    "journey-profile.html",
    "team-profile.html",
    "venue-profile.html",
    "year.html",
    "index.html",
]
for name in linked_pages:
    path = ROOT / name
    if not path.is_file():
        errors.append(f"missing {name}")
        continue
    text = path.read_text(encoding="utf-8")
    # Editable legacy templates may still emit event.html?id=...; clean-urls.js
    # deterministically rewrites those links to /events/{id}/ on generated pages.
    if "event.html?id=" not in text and "/events/" not in text:
        errors.append(f"{name} does not deep-link to exact event passports")

sitemap = ROOT / "sitemap.xml"
if not sitemap.is_file():
    errors.append("missing sitemap.xml")
else:
    try:
        tree = ET.parse(sitemap)
        ns = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
        urls = {n.text.strip() for n in tree.findall("sm:url/sm:loc", ns) if n.text}
        for item in ranked:
            event_id = item.get("event_id")
            expected = f"{ORIGIN}/events/{event_id}/"
            if expected not in urls:
                errors.append(f"sitemap missing ranked first-class Event Passport URL: {expected}")
    except Exception as exc:
        errors.append(f"could not parse sitemap.xml: {exc}")

if errors:
    print("\n".join("ERROR: " + e for e in errors))
    sys.exit(1)

print(
    f"OK: exact event template, {len(by_id)} first-class Event Passport pages, {len(linked_pages)} linking views, "
    f"legacy query compatibility, and {len(ranked)} Personal Canon event URLs validated."
)
